services:
  strapi:
    build:
      context: ../..
      dockerfile: docker/strapi/Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      NODE_ENV: 'development'
      PORT: ${PORT}
      DATABASE_CLIENT: sqlite
    working_dir: /usr/src/strapi
    stdin_open: true  # Позволяет использовать интерактивный режим
    tty: true         # Включает терминал

