services:
  ${APP_NAME}-nextjs:
    build:
      context: ../..
      dockerfile: docker/nextjs/Dockerfile
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      NODE_ENV: 'development'
      PORT: ${FRONTEND_PORT}
    working_dir: /usr/app
    stdin_open: true  # Позволяет использовать интерактивный режим
    tty: true         # Включает терминал

