services:
  next-app:
    build:
      context: ../..
      dockerfile: docker/nextjs/Dockerfile
    ports:
      - 3000:3000
    working_dir: /usr/app
    stdin_open: true  # Позволяет использовать интерактивный режим
    tty: true         # Включает терминал

