services:
  ${APP_NAME}-nextjs:
    build:
      context: ../..
      dockerfile: docker/nextjs/Dockerfile
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      NODE_ENV: 'development'
      PORT: ${FRONTEND_PORT}
    volumes:
      - type: bind
        source: ../../frontend
        target: /usr/app
    stdin_open: true
    tty: true
    networks:
      - ${APP_NAME}-network